Features/search bar
Ozanyurdakul98/capstone-project pull request #15
Opened 2022-10-23 14:44 UTC by Ozanyurdakul98

components/DatePicker/default.css
components/DatePicker/styles.css
These are files from react-date-range component library brought to the root from node_modules to add custom styles and keep it form being overwritten by npm install.

db/fakedata.js
I changed my mind and moved the fake data to a seperate file

2022-10-23 15:15 UTC, Ozanyurdakul98 commented on components/DatePicker/styles.css
> +.rdrInputRangeInput {
don't review. this is from component-library from node_modules

2022-10-23 15:16 UTC, Ozanyurdakul98 commented on db/fakedata.js
> +};
Just moved it from page component to here. Don't review, already has been reviewed

2022-10-23 15:16 UTC, Ozanyurdakul98 commented on components/DatePicker/default.css
> +}
don't review. this is from component-library from node_modules

2022-10-24 09:18 UTC, F-Kirchhoff commented on components/DatePicker/styles.css
> +.rdrInputRangeInput {
Please solve the restyling purely via styled components - you can research how to do that or write a question on Github Discussions. If you work with styled components you don't use .css files anymore to have a coherent way of writing your styles.

2022-10-24 09:52 UTC, F-Kirchhoff requested changes
This PR was too big. Please make sure to create smaller PRs in the future, you can do multiple PRs for one user story. 
There are some things to improve here, please make sure to write DRY code, that is not that convoluted. If you struggle with the size of the search options, please reduce the functionality until you have a better overview. You can create multiple PRs by introducing one search option at a time for example.

Generally it might be helpful to create more components to reduce the size of an individual component. This now is very hard to read and to understand.

2022-10-24 09:52 UTC, F-Kirchhoff commented on components/ListingCards.jsx
> +										key={nanoid()}
This would lead to problems, you reassign a new random key to all of your components in the list with each rerender. This way react cannot keep track about the individual elements in the list. You need to apply nanoid only once when the data is created.

2022-10-24 09:52 UTC, F-Kirchhoff commented on components/SearchBar.jsx
> +	const search = (event) => {
the name of your function should indicate that it is a function like "onSearch" or 'handleSearch'

2022-10-24 09:52 UTC, F-Kirchhoff commented on components/SearchBar.jsx
> +			return alert('please enter a location');
Why do you return the undefined of the alert? 
```suggestion 
			alert('please enter a location');
			return
```

2022-10-24 09:52 UTC, F-Kirchhoff commented on components/SearchBar.jsx
> +			return setSearchInput('');
Why do you return here?

2022-10-24 09:52 UTC, F-Kirchhoff commented on components/SearchBar.jsx
> +			return setSearchInput('');
And here?

2022-10-24 09:52 UTC, F-Kirchhoff commented on components/SearchBar.jsx
> +	const [dateButton, setDateButton] = useState(true);
please choose a name that indicates a boolean like dateButtonActive or dateButtonHighlight

2022-10-24 09:52 UTC, F-Kirchhoff commented on components/SearchBar.jsx
> +	const refOne = useRef(null);
please use more descriptive names here, I have no clue what refOne and refTwo should do.

2022-10-24 09:52 UTC, F-Kirchhoff commented on components/SearchBar.jsx
> +		document.addEventListener('click', hideOnOutsideClick, true);
Why do you add two event listeners? You should find a solution where you don't install an event listener on the document for this task, this quickly leads to bugs.

2022-10-24 09:52 UTC, F-Kirchhoff commented on components/SearchBar.jsx
> +	const handleGuestInput = () => {};
this is a function that does nothing. please remove it for now

2022-10-24 09:52 UTC, F-Kirchhoff commented on components/SearchBar.jsx
> +		}
You can write this code only using the setter function once!

2022-10-24 09:52 UTC, F-Kirchhoff commented on components/SearchBar.jsx
> +	};
same here

2022-10-24 09:52 UTC, F-Kirchhoff commented on components/SearchBar.jsx
> +						)}
please only toggle the button class name instead of the whole button

2022-10-24 09:52 UTC, F-Kirchhoff commented on components/SearchBar.jsx
> +							</button>
same here

2022-10-24 09:52 UTC, F-Kirchhoff commented on components/SearchBar.jsx
> +					<div className=' flex w-screen flex-col items-center justify-center'>
and here

2022-10-24 09:52 UTC, F-Kirchhoff commented on pages/_app.jsx
>  import GlobalStyle from '../components/GlobalStyle';
Please only use .js files

2022-10-24 09:52 UTC, F-Kirchhoff commented on pages/search/all.jsx
> +function Search() {
Please use a name that reflects that you see the search results here

2022-10-24 09:52 UTC, F-Kirchhoff commented on pages/search/all.jsx
> +	const [search, setSearch] = useState(listings);
you don't need a state if it won't change

2022-10-24 09:52 UTC, F-Kirchhoff commented on pages/search/index.jsx
> +	const query = JSON.parse(JSON.stringify(context.query));
Why do you do this?

2022-10-24 09:52 UTC, F-Kirchhoff commented on pages/search/index.jsx
> +const listings = fakeData.studioListings;
you can simply use fakeData.studioListings inside your useState

2022-10-24 09:52 UTC, F-Kirchhoff commented on pages/search/index.jsx
> +			return setSearch(filteredLoc);
This is super wet code, please try to find a better solution and don't repeat yourself that much.

2022-10-24 09:52 UTC, F-Kirchhoff commented on pages/search/index.jsx
> +			let filteredLoc = listings.filter((listings) =>
please find a way to filter all queries at once instead of doing it one step after another. We don't want to use let in your code whenever it is possible.

2022-10-24 09:52 UTC, F-Kirchhoff commented on pages/search/index.jsx
> +							key={nanoid()}
don't use nanoid inside a map, as explained above.

2022-10-24 10:55 UTC, Ozanyurdakul98 commented on components/ListingCards.jsx
> +										key={nanoid()}
Ich hatte hier eine Fehlermeldung, weil irgendwie mehrmals eine Karten gerendert wurden und eine ID zweimal gerendert wird. Diese Fehlermeldung kam am Anfang nicht als ich Index als key hatte. Dann kam sie und jetzt gehts wieder nur mit Index. Mal gucken, ich meld mich wenn es wieder Probleme gibt. habe es aber wieder auf Index als key geändert, statt nanoID.

2022-10-24 11:07 UTC, Ozanyurdakul98 commented on components/SearchBar.jsx
> +			return setSearchInput('');
here the line of code is not needed. thanks

2022-10-24 11:08 UTC, Ozanyurdakul98 commented on components/SearchBar.jsx
> +			return setSearchInput('');
somehow I thought it would be better to end the function here after this if condition was run trough. But now I think I don't need it ..

2022-10-24 11:51 UTC, Ozanyurdakul98 commented on components/SearchBar.jsx
> +		document.addEventListener('click', hideOnOutsideClick, true);
to be done

2022-10-25 10:02 UTC, Ozanyurdakul98 commented on pages/search/index.jsx
> +const listings = fakeData.studioListings;
This unfortunately I won't change, because listings I use more often inside the component. its more comfortable to reed so

2022-10-25 12:47 UTC, F-Kirchhoff requested changes
This is already looking better. There are still some naming problems and some parts of your code need a bit more attention. But good progress already.

2022-10-25 12:47 UTC, F-Kirchhoff commented on components/ListingCards.js
>  										className='rounded-full bg-red-200 px-[9px] text-xs sm:text-sm md:text-lg'
Every time you map, you are creating the same type of substructure, therefore we want to use an unsorted list for this task most of the times. Please change it in that way, that you have an 'ul' with each item that was generated by the map is a 'li'

2022-10-25 12:47 UTC, F-Kirchhoff commented on components/ListingCards.js
> +										key={index}
please don't use the index if it is possible. either your data structure should have an id for each element or use something unique from the single data element.

2022-10-25 12:47 UTC, F-Kirchhoff commented on components/SearchBar.js
> +					id: nanoid(),
what do you use this id for?

2022-10-25 12:47 UTC, F-Kirchhoff commented on components/SearchBar.js
> -			return setSearchInput('');
maybe you still need the setSearchInput here.

2022-10-25 12:47 UTC, F-Kirchhoff commented on components/SearchBar.js
> +	const closeSearchContainer = useRef(null);
the names sound like functions or booleans, please rename to: 
'calendarContainerRef' and 'searchContainerRef'

2022-10-25 12:47 UTC, F-Kirchhoff commented on components/SearchBar.js
>  		}
Normally you would solve this issue by adding a transparent div in the background which covers the whole screen. This div gets an eventlistener wich toggles the visibilty of the input. Ask Sebastian about it, he plans to create such a component.

2022-10-25 12:47 UTC, F-Kirchhoff commented on components/SearchBar.js
> +	const [guestsButtonActive, setGuestsButtonActive] = useState('');
didn't we planned to replace these single true / false states with a single state called "openPanel", which holds either 'date', 'guests' or 'services'?

2022-10-25 12:47 UTC, F-Kirchhoff commented on components/SearchBar.js
> +						</button>
this is much better!

2022-10-25 12:47 UTC, F-Kirchhoff commented on components/SearchBar.js
> +						{dateButtonActive && (
here you need to use the new state 'activePanel === "date"'

2022-10-25 12:47 UTC, F-Kirchhoff commented on db/fakedata.js
> +			_id: `${nanoid()}`,
you can omit the template string:
``` 
_id: nanoid()
```

2022-10-25 12:47 UTC, F-Kirchhoff commented on pages/search/index.js
> +		if (checkInDay === weekdayMap[checkInDay]) {
this will always be true, since weekdayMap[0] === 0, weekdayMap[1] === 1 etc.

2022-10-25 12:47 UTC, F-Kirchhoff commented on pages/search/index.js
> +			return refreshData();
please return after refreshData:
```
refreshData()
return
```

2022-10-25 12:47 UTC, F-Kirchhoff commented on pages/search/index.js
> +						<ListingCards
Please use singular when this component only renders one Card. In general: 
- plural for arrays
- singular for objects and other individual data elements
- something like isOpen / isAdmin / isHidden for booleans
- function name starting with a verb.

2022-10-25 12:47 UTC, F-Kirchhoff commented on pages/search/index.js
> +		});
As for now you don't need these two constants

2022-10-25 12:50 UTC, F-Kirchhoff commented on pages/search/index.js
> +		});
btw: I didn't called the weekdayMap a Map because I use the method map, it is called a Map because it "maps" or translates the numbers 0-6 to the weekday names. This procedure of linking one element of one set with another element of another set is called "mapping" (which happens exactly in the method map, where we project each element form our array onto a new element in a new array)

2022-10-25 13:03 UTC, Ozanyurdakul98 commented on components/SearchBar.js
> +					id: nanoid(),
There is an error that occasionally happens..->. "fail to hard push to same url" or something like this. But if it happens again ill come back to you

2022-10-25 13:04 UTC, Ozanyurdakul98 commented on components/SearchBar.js
> -			return setSearchInput('');
No I don't. the purpose of this was to close the search filters option. but I don't do event.preventDefault, soo its ok

2022-10-25 13:06 UTC, Ozanyurdakul98 commented on components/SearchBar.js
> -			return setSearchInput('');
but if search input is empty, there's no search filter window to close ...

2022-10-25 13:09 UTC, Ozanyurdakul98 commented on components/SearchBar.js
>  		}
But what you say I thought about it for a second. but I thought in solving it with Grid and to think about that was very frustrating

2022-10-26 08:38 UTC, F-Kirchhoff commented on components/SearchBar.js
> +	const handleCTCSearch = () => {
I don't know what that means, please use a more descriptive variable. It is ok if it is getting long.

2022-10-26 08:39 UTC, F-Kirchhoff commented on components/SearchBar.js
> +	const handleCTCCalendar = () => {
same here

2022-10-26 08:41 UTC, F-Kirchhoff commented on components/SearchBar.js
> +				<>
you don't need this fragment

2022-10-26 08:43 UTC, F-Kirchhoff commented on components/SearchBar.js
> +										<>
you don't need the fragment here

2022-10-26 08:46 UTC, F-Kirchhoff commented on pages/search/index.js
> +	const filteredStudioListings = filterStudioListings();
if you write a function just to call it afterwards, you can just write the code inside the function immediately without the function.

2022-10-26 08:47 UTC, F-Kirchhoff commented on pages/search/index.js
> +				{filteredStudioListings.map(
thats a good name!

2022-10-26 08:47 UTC, F-Kirchhoff commented on styles/globals.css
>  	} */
please remove all outcommented code

2022-10-26 08:49 UTC, F-Kirchhoff commented on pages/search/index.js
> +					studio.openingCustom?.[weekdays[checkInDay]] ||
still, please remove the ?. in front of the bracket notation, this is like doing this:
```
studio.openingCustom?..monday
```

2022-10-26 08:50 UTC, F-Kirchhoff commented on pages/search/index.js
> +					studio.openingCustom?.[weekdays[checkInDay]] ||
You can't double access the values of an object, use dot notation OR bracket notation, not both. (Here we need the bracket notation, since we want to use a variable key name (i.e. the key "monday" - "sunday")

2022-10-26 11:10 UTC, merged

2022-10-26 11:12 UTC, F-Kirchhoff requested changes
I am so sorry but I still found something. Please ask Thomas Foeldi to check the code when you are done with it.

2022-10-26 11:12 UTC, F-Kirchhoff commented on components/ClickToClose.js
>  import React from 'react';
Ah sorry, I forgot to mention that you need to rename the component file to BackgroundOverlay

2022-10-26 11:12 UTC, F-Kirchhoff commented on pages/search/index.js
> +				{filterStudioListings().map(
Ah this is not what I meant 🙈 . You don't have to use a function at all, just write the code into the component directly!
```js
// remove the function declaration here
const weekdays = [
	'sunday',
	'monday',
	'thuesday',
	'wednesday',
	'thursday',
	'friday',
	'saturday',
];
const checkInDay = new Date(location.startDate).getDay();
if (
	router.query.location !== searchFilter.location ||
	router.query.noOfGuests !== searchFilter.noOfGuests ||
	router.query.servicesSelected !== searchFilter.servicesSelected ||
	router.query.startDate !== searchFilter.startDate
) {
	setSearchFilter(location);
}
const filteredStudioListings = listings
	.filter((studio) =>
		studio.location?.toLowerCase().includes(searchFilter.location?.toLowerCase())
	)
	.filter((studio) => studio.maxGuests >= searchFilter.noOfGuests)
	.filter((studio) =>
		studio.services
			.map((studio) => {
				return studio.toLowerCase();
			})
			.includes(searchFilter.servicesSelected.toLowerCase())
	)
	.filter(
		(studio) =>
			studio.openingCustom?.[weekdays[checkInDay]] ||
			studio.openingOption === 'Always Available' ||
			studio.openingOption === 'On Request'
			studio.openingOption === 'On Request' ||
			studio.openingCustom[weekdays[checkInDay]]
	);
const date = new Date(location.startDate);
return <> ...
```