Features/form submit
Ozanyurdakul98/capstone-project pull request #33
Opened 2022-11-02 10:39 UTC by Ozanyurdakul98

Userstory https://github.com/Ozanyurdakul98/capstone-project/issues/32

Please check if everything is ok. Next storys are validation and user login

2022-11-02 10:40 UTC, Ozanyurdakul98 commented on models/StudioListing.js
> +// );
sorry I delete this with approval.

2022-11-03 11:56 UTC, Kheirah requested changes
Please run Prettier in all your project files. The format is difficult to read when there are so many spaces preceding every line of code.

Then have a look at my comments and adjust your code accordingly =)

2022-11-03 11:56 UTC, Kheirah commented on components/ListingCard.js
>  	const slicedServices = services.slice(0, 3).map((service) => service);
Is there a reason why you slice the number of services down to 3 entries?
What is more, your chained map function doesn't do anything, really You're mapping every service to itself.

2022-11-03 11:56 UTC, Kheirah commented on components/ListingCard.js
>  							{locationFeatures.sleepover ? <MdBed className='icon' /> : ''}
Whenever you don't want to display an element in jsx, you'd conventionally use `null` instead of an empty string.
Please change it for every occurence in this file.

2022-11-03 11:56 UTC, Kheirah commented on models/StudioListing.js
> +// );
Yes, please do =)

2022-11-03 11:56 UTC, Kheirah commented on pages/api/seed-listings.js
> +	// await StudioListing.insertMany(fakeData.studioListings);
Clean up code that you no longer need. The file says "seed-listings" and I'd expect it to do exactly that and not delete everything.

2022-11-03 13:40 UTC, Kheirah approved these changes
Good job!

2022-11-04 16:02 UTC, merged